### ISSUE TITLE
Build libhybris master branch failed

### ISSUE THREAD

**Issue by 0312birdzhang** [mer-hybris/libhybris#38]
With this commit : Convert to submodule  https://github.com/mer-hybris/libhybris/commit/bc074a1630caa929d8e853ed1fff05e1f02a92fa

dhd helper script not clone submodle when init.
https://github.com/mer-hybris/droid-hal-device/blob/fdb359e2547c3e5dd28afd4fb5fdca42e5b8327e/helpers/util.sh#L169

**Comment by mlehtima** [comment]
This issue will be fixed once https://github.com/mer-hybris/droid-hal-device/pull/182 is merged. Hopefully soon.
